Lexnarro/Controllers/OtherUsersController.cs
using Lexnarro.HelperClasses;
using Lexnarro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using System.Net;

namespace Lexnarro.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OtherUsersController : Controller
    {

        private LaxNarroEntities db = null;
        private readonly ToasterMessage toastNotifications = null;


        public OtherUsersController()
        {
            db = new LaxNarroEntities();
            toastNotifications = new ToasterMessage();
        }



        // GET: OtherUsers
        public ActionResult Index()
        {
            if (TempData["message"] != null)
                ViewBag.message = TempData["message"].ToString();

            return View();
        }



        public ActionResult GetUsers()
        {
            DateTime dt = DateTime.Today;
            var user_Profile = db.User_Transaction_Master.Include(u => u.User_Profile).Include(z => z.User_Profile.Country_Master)
               .Include(z => z.User_Profile.State_Master).Include(z => z.User_Profile.State_Master1).Where(z => z.End_Date < dt
               || z.Payment_Status == "N/A" && z.User_Profile.Role_Master.Name != "Admin").ToList();

            var users = user_Profile.Select(S => new
            {
                S.Id,
                S.User_ID,
                S.User_Profile.FirstName,
                S.User_Profile.LastName,
                Country = S.User_Profile.Country_Master.Name,
                State = S.User_Profile.State_Master.Name,
                StateEnrolled = S.User_Profile.State_Master1.Name,
                S.User_Profile.EmailAddress
            });

            return Json(new { data = users }, JsonRequestBehavior.AllowGet);
        }



        public ActionResult Details(decimal? id)
        {
            User_Profile user_Profile = null;

            if (UserHelper.GetUserRole() == "Admin")
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                user_Profile = db.User_Profile.Find(id);

                if (user_Profile == null)
                    return HttpNotFound();

            }
            else
            {
                if (id != Convert.ToDecimal(UserHelper.GetUserId()))
                {
                    TempData["message"] = ToasterMessage.Message(ToastType.warning, "Unauthorized Access");
                    return RedirectToAction("Index");
                }

                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                user_Profile = db.User_Profile.Find(id);

                if (user_Profile == null)
                    return HttpNotFound();
            }

            return View(user_Profile);
        }



        #region OTHER USERS AND TRANSACTION RECORDS

        public ActionResult Payment(decimal? id)
        {
            ViewBag.id = id;
            return View();
        }


        public ActionResult GetTransactions(decimal id)
        {
            IQueryable<User_Transaction_Master> userTransaction = db.User_Transaction_Master.Include(u => u.User_Profile).
                Include(u => u.Rate_Card).Include(u => u.Plan_Master).Where(u => u.User_ID == id);

            var transactions = userTransaction.ToList().Select(item => new
            {
                item.Id,
                item.User_ID,
                item.User_Profile.FirstName,
                item.User_Profile.LastName,
                item.Plan_Master.Plan,
                item.Amount,
                StartDate = item.Start_Date.ToShortDateString(),
                EndDate = item.End_Date.ToString().Split(' ')[0],
                PaymentDate = item.Payment_Date.ToString().Split(' ')[0],
                item.Payment_Status,
                item.Transection_ID,
                item.Status,
                item.Invoice_No
            });

            return Json(new { data = transactions }, JsonRequestBehavior.AllowGet);
        }

        
        public ActionResult PaymentDetails(decimal id)
        {
            User_Transaction_Master userTransaction = db.User_Transaction_Master.Include(u => u.User_Profile).
                Include(u => u.Rate_Card).Include(u => u.Plan_Master).Where(u => u.Id == id).SingleOrDefault();

            if (userTransaction == null)
                return HttpNotFound();

            return View(userTransaction);
        }

        #endregion



        #region OTHER USERS AND CPD RECORDS

        public ActionResult Training(decimal? id)
        {
            ViewBag.id = id;
            return View();
        }


        public ActionResult GetTraining(decimal id)
        {
            var userTraining = db.User_Training_Transaction.Include(x => x.User_Profile).Include(x => x.Category_Master)
                 .Include(x => x.Activity_Master).Include(x => x.Sub_Activity_Master).Include(x => x.State_Master).Where(x => x.User_Id == id).ToList();

            var training = userTraining.Select(S => new
            {
                S.Id,
                S.User_Id,
                S.Date,
                S.User_Profile.FirstName,
                S.User_Profile.LastName,
                Country = S.User_Profile.Country_Master.Name,
                StateEnrolled = S.State_Master.Name,
                Category = S.Category_Master.Name,
                Activity = S.Activity_Master.Name,
                SubActivity = (S.SubActivity_Id == null) ? "" : S.Sub_Activity_Master.Name,
                S.Hours,
                S.Provider,
                S.Financial_Year,
                S.User_Profile.EmailAddress
            });

            return Json(new { data = training }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult TrainingDetails(decimal? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            User_Training_Transaction userTraining = db.User_Training_Transaction.Include(u => u.User_Profile).
                Include(u => u.User_Training_Status).Where(u => u.Id == id).SingleOrDefault();

            if (userTraining == null)
                return HttpNotFound();

            return View(userTraining);
        }

        #endregion


        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();

            base.Dispose(disposing);
        }
    }
}

Lexnarro/Controllers/TrainingController.cs
using Lexnarro.HelperClasses;
using Lexnarro.Models;
using SelectPdf;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Lexnarro.Controllers
{
    [Authorize]
    public class TrainingController : Controller
    {
        private LaxNarroEntities db = new LaxNarroEntities();

        // GET: User_Training_Transaction

        public ActionResult Index(string financialYear)
        {
            decimal userID = Convert.ToDecimal(UserHelper.GetUserId());

            #region DELETE EXISTING FILE

            try
            {
                if (System.IO.File.Exists(Server.MapPath("~/Reports/TrainingReport_" + userID + ".pdf")))
                {
                    System.IO.File.Delete(Server.MapPath("~/Reports/TrainingReport_" + userID + ".pdf"));
                }
            }
            catch (Exception)
            {
                //throw;
            }

            #endregion

            string finYear = string.Empty;

            if (financialYear == null)
            {
                finYear = GetFinancialYear();
            }
            else
            {
                finYear = financialYear;
            }

            ViewBag.fy = GetFinancialYear(); 
            List<User_Transaction_Master> demoUser = db.User_Transaction_Master.Include(x => x.Plan_Master)
                .Where(x => x.Plan_Master.Plan == "Demo" && x.User_ID == userID).ToList();

            List<User_Training_Transaction> userRecordsCount = db.User_Training_Transaction.Where(x => x.User_Id == userID).ToList();

            if (demoUser.Count > 0)
            {
                ViewBag.userPlan = "Demo";

                if (userRecordsCount.Count >= 0 && userRecordsCount.Count <= 4)
                {
                    ViewBag.RowCount = userRecordsCount.Count;
                }
                else
                {
                    ViewBag.RowCount = userRecordsCount.Count;
                }
            }
            else
            {
                ViewBag.userPlan = "Not Demo";

                if (userRecordsCount.Count > 0)
                {
                    ViewBag.RowCount = userRecordsCount.Count;
                }
                else
                {
                    ViewBag.RowCount = 0;
                }
            }

            ViewBag.CurrentCPDYear = GetFinancialYear();

            List<SelectListItem> fy = new List<SelectListItem>();

            fy = (from s in db.User_Training_Transaction
                  where s.User_Id == userID
                  orderby s.Date
                  select new SelectListItem
                  {
                      Text = s.Financial_Year,
                      Value = s.Financial_Year
                  }).Distinct().ToList();

            foreach (SelectListItem item in fy)
            {
                if (item.Value == finYear)
                {
                    item.Selected = true;
                    break;
                }
            }

            ViewBag.financialYear = fy;

            if (TempData["message"] != null)
            {
                ViewBag.message = TempData["message"].ToString();
            }

            return View();
        }


        public ActionResult GetTraining(decimal id, string finYear)
        {
            decimal userId = Convert.ToDecimal(UserHelper.GetUserId());

            if (id != userId)
            {
                TempData["message"] = ToasterMessage.Message(ToastType.warning, "Unauthorized access.");
                return RedirectToAction("Index");
            }

            List<User_Training_Status> userTraining = db.User_Training_Status.Include(x => x.User_Profile).Include(x => x.Category_Master)
                 .Include(x => x.Activity_Master).Include(x => x.Sub_Activity_Master).Include(x => x.User_Training_Transaction)
                 .Where(x => x.User_Id == userId && x.Financial_Year == finYear && x.Units_Done != 0).ToList();

            //var userTransactionData = db.User_Training_Status.Where(u => u.User_Id == id && u.Financial_Year == finYear).ToList();

            decimal? totalUnits = 0;

            totalUnits = userTraining.Select(x => x.Units_Done).Sum();

            //foreach (User_Training_Status row in userTraining)
            //{
            //    totalUnits += (int)Math.Floor(Convert.ToDecimal(row.Units_Done));
            //}

            ViewBag.TotalUnits = totalUnits;

            var training = userTraining.Select(S => new
            {
                S.Id,
                S.User_Id,
                S.Training_Transaction_ID,
                Date = S.User_Training_Transaction.Date.ToString().Split(' ')[0],
                S.User_Profile.FirstName,
                S.User_Profile.LastName,
                Country = S.User_Profile.Country_Master.Name,
                StateEnrolled = S.User_Profile.State_Master1.Name,
                Category = S.Category_Master.Name,
                Activity = S.Activity_Master.Name,
                SubActivity = (S.SubActivity_Id == null) ? "" : S.Sub_Activity_Master.Name,
                S.User_Training_Transaction.Hours,
                S.User_Training_Transaction.Provider,
                S.Financial_Year,
                S.Units_Done,
                S.User_Profile.EmailAddress,
                TotalUnits = totalUnits,
                S.Received_By_Forwarding,
                S.User_Training_Transaction.Has_been_Forwarded,
                rowCount = userTraining.Count
            });

            return Json(new { data = training }, JsonRequestBehavior.AllowGet);
        }


        //public ActionResult GetData(string finYear)
        //{
        //    string userRole = UserHelper.GetUserRole();
        //    decimal userId = Convert.ToDecimal(UserHelper.GetUserId());
        //    string finanacialYear = string.Empty;

        //    if (finYear == null)
        //    {
        //        finanacialYear = GetFinancialYear();
        //    }
        //    else
        //    {
        //        finanacialYear = finYear;
        //    }

        //    //IQueryable<User_Training_Status> user_Training_Transaction = db.User_Training_Status.Include(u => u.Activity_Master)
        //    //    .Include(u => u.Category_Master).Include(u => u.User_Profile).Include(u => u.User_Training_Transaction)
        //    //    .Where(u => u.Financial_Year == finanacialYear);

        //    //if (userRole == "User")
        //    //{
        //        var user_Training_Transaction = db.User_Training_Status.Include(u => u.Activity_Master)
        //       .Include(u => u.Category_Master).Include(u => u.User_Profile)
        //       .Include(u => u.User_Training_Transaction).Where(u => u.User_Id == userId && u.Financial_Year == finanacialYear);
        //    //}


        //    var subData = user_Training_Transaction.ToList().Select(S => new
        //    {
        //        S.Id,
        //        State = S.User_Profile.State_Master1.Name,
        //        Category = S.Category_Master.Name,
        //        Activity = S.Activity_Master.Name,
        //        Subactivity = (S.SubActivity_Id == null) ? "" : S.Sub_Activity_Master.Name,
        //        Units = S.Units_Done,
        //        S.User_Training_Transaction.Hours,
        //        S.Financial_Year,
        //        S.User_Training_Transaction.Forwardable,
        //        S.User_Training_Transaction.Has_been_Forwarded,
        //        S.User_Training_Transaction.Provider,
        //        S.User_Training_Transaction.Descrption,
        //        S.User_Training_Transaction.UploadedFileName,
        //        Role = S.User_Training_Transaction.Your_Role,
        //        Date = S.User_Training_Transaction.Date.ToString().Split(' ')[0],
        //        S.User_Id
        //    });

        //    return Json(new { data = subData }, JsonRequestBehavior.AllowGet);
        //}


        public ActionResult Details(decimal? id)
        {
            decimal userID = Convert.ToDecimal(UserHelper.GetUserId());

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            User_Training_Transaction user_Training_Transaction = db.User_Training_Transaction.Find(id);

            if (user_Training_Transaction.User_Id != userID)
            {
                TempData["message"] = ToasterMessage.Message(ToastType.warning, "Unauthorized access.");
                return RedirectToAction("Index");
            }
            

            if (user_Training_Transaction == null)
            {
                return HttpNotFound();
            }

            //CheckCurrentUserPlan(userID);

            //Create financial year viewbag and check it to wheather to show edit button or not.
            ViewBag.financialYear = GetFinancialYear();

            return View(user_Training_Transaction);
        }


        // GET: User_Training_Transaction/Create
        public ActionResult Create()
        {
            decimal userID = Convert.ToDecimal(UserHelper.GetUserId());

            //ViewBag.CurrentDate = DateTime.Today;

            //var state = (from s in db.User_Profile
            //             join c in db.State_Master on s.StateEnrolled equals c.ID
            //             where s.ID == userID
            //             select new { c.ID, c.Name }).ToList();

            //var ds = state.ToList();

            decimal stateId = Convert.ToDecimal(UserHelper.GetUserStateEnrolledId());

            //-----------Checking for no of records and demo account-----------

            var demoRecords = (from a in db.User_Transaction_Master
                               join b in db.User_Profile on a.User_ID equals b.ID

Lexnarro/Views/OtherUsers/Details.cshtml
@model Lexnarro.Models.User_Profile

@using Lexnarro.HelperClasses;

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div class="row">
    <div class="form-horizontal col-lg-6 col-lg-offset-2">
        <div class="alert alert-info fade in">
            <h4>User</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.Label("First Name")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FirstName)
                </dd>

                <dt>
                    @Html.Label("Last Name")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LastName)
                </dd>

                <dt>
                    @Html.Label("Other Name")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OtherName)
                </dd>

                <dt>
                    @Html.Label("Address")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Address)
                </dd>

                <dt>
                    @Html.Label("Street Number")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StreetNumber)
                </dd>

                <dt>
                    @Html.Label("Street Name")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StreetName)
                </dd>

                <dt>
                    @Html.Label("Postal Code")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PostCode)
                </dd>

                <dt>
                    @Html.Label("Suburb")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Suburb)
                </dd>

                <dt>
                    @Html.Label("State Enrolled")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.State_Master1.Name)
                </dd>

                <dt>
                    @Html.Label("Law Society Number")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LawSocietyNumber)
                </dd>

                <dt>
                    @Html.Label("Firm")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Firm)
                </dd>

                <dt>
                    @Html.Label("Email")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EmailAddress)
                </dd>

                <dt>
                    @Html.Label("Phone Number")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PhoneNumber)
                </dd>

                <dt>
                    @Html.Label("User Name")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserName)
                </dd>


                <dt>
                    @Html.Label("Password")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Password)
                </dd>

                @*<dt class="hidden">
                    @Html.Label("Password")
                </dt>

                <dd class="hidden">
                    @Html.DisplayFor(model => model.Password)
                </dd>*@

                <dt>
                    @Html.Label("Date")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Date)
                </dd>

                <dt>
                    @Html.Label("Country Name")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Country_Master.Name)
                </dd>

                <dt>
                    @Html.Label("User Role")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Role_Master.Name)
                </dd>

                <dt>
                    @Html.Label("State Name")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.State_Master.Name)
                </dd>

            </dl>
        </div>
    </div>
</div>

<p>
    @if (UserHelper.GetUserRole() == "Admin")
    {
        @Html.ActionLink("Transaction History", "Payment", "OtherUsers",
                new { id = Model.ID }, htmlAttributes: new { @class = "btn btn-primary form-group" })
        <span>|</span>
        @Html.ActionLink("CPD Records", "Training", "OtherUsers",
            new { id = Model.ID }, htmlAttributes: new { @class = "btn btn-primary form-group" })<span>|</span>
    }

    @if (UserHelper.GetUserRole() == "Admin")
    {
        if (Model.Role_Master.Name == "Admin")
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, htmlAttributes: new { @class = "btn btn-info" })<span>|</span>
        }
    }
    else
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, htmlAttributes: new { @class = "btn btn-info" })<span>|</span>
    }

    @Html.ActionLink("Back to List", "Index", "OtherUsers", null, htmlAttributes: new { @class = "btn btn-primary" })
</p>

Lexnarro/Views/OtherUsers/Payment.cshtml
@{
    ViewBag.Title = "Payment";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var id = Convert.ToDecimal(ViewBag.id);
}

<h2>Transaction List</h2>
<br />
<h4><b>Name : <span id="name"></span></b></h4>
<br />
<section class="panel">
    <div class="panel-body">
        <table class="table table-hover" id="dataTable">
            <thead>
                <tr>
                    <th></th>
                    <th>
                        Plan
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Start Date
                    </th>
                    <th>
                        End Date
                    </th>
                    <th>
                        Transaction Id
                    </th>
                    <th>
                        Payment Date
                    </th>
                    <th>
                        Invoice No
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
            </thead>

        </table>
        <h4>
            <b>
                Total Amount : <span id="totalamount"></span>
            </b>
        </h4>
        <br />

        <p>
            @Html.ActionLink("Back to List", "Details", "OtherUsers", new { id = id }, htmlAttributes: new { @class = "btn btn-primary" })
        </p>

    </div>


    @section JavaScript{
        @Html.Raw(ViewBag.message)
    }

    @section scripts
    {
        <script>
            $(function () {                
                var t = $('#dataTable').DataTable({
                    theme: 'bootstrap',
                    responsive: true,
                    autoWidth: false,
                    "footerCallback": function (row, data, start, end, display) {
                        var api = this.api(), data;
                        // Remove the formatting to get integer data for summation
                        var intVal = function (i) {
                            return typeof i === 'string' ? i.replace(/[\$,]/g, '') * 1 : typeof i === 'number' ? i : 0;
                        };

                        // totalAmount over all pages
                        total_amount = api.column(2).data().reduce(function (a, b) {
                            return (intVal(a) + intVal(b)).toFixed(2);
                        }, 0);

                        // total_page_amount over this page
                        total_page_amount = api.column(2, { page: 'current' }).data().reduce(function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0);

                        total_page_amount = parseFloat(total_page_amount);
                        total_amount = parseFloat(total_amount);
                        // Update footer
                        $('#totalamount').html(total_amount);
                    },

                    "columnDefs": [{
                        "searchable": false,
                        "orderable": false,
                        "targets": [0]
                    }],
                    "order": [[1, 'asc']],
                    "ajax": {
                        "url": '/OtherUsers/GetTransactions',
                        "data":{id : @id},
                        "type": 'get',
                        "datatype": "json"
                    },
                    "columns": [
                        { "data":null },
                        {
                            "data": "Plan"
                        },
                        { "data": "Amount" },
                        { "data": "StartDate" },
                        { "data": "EndDate" },
                        //{ "data": "Payment_Status" },
                        { "data": "Transection_ID" },
                        //{ "data": "Status" },
                        { "data": "PaymentDate" },
                        { "data": "Invoice_No"},
                         {
                             "data": "Id", render: (function (data, type, row) {
                                 //if (row.ID == userId) {
                                 //    return ' <a href="/User/ActiveUserDetails/' + data + '" class="btn btn-primary">Details</a>';
                                 //}
                                 $('#name').text(row.FirstName + ' ' + row.LastName);
                                 return '<a href="/OtherUsers/PaymentDetails/' + data + '" class="btn btn-info">Details</a>';
                             })
                         }
                    ]
                });
                t.on('order.dt search.dt', function () {
                    t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                        cell.innerHTML = i + 1;
                    });
                }).draw();
            });
        </script>
    }
</section>

Lexnarro/Views/OtherUsers/PaymentDetails.cshtml
@model Lexnarro.Models.User_Transaction_Master

@{
    ViewBag.Title = "PaymentDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var Id = ViewBag.id;
}

<h2>Transaction Details</h2>

<div class="row">
    <div class="form-horizontal col-lg-6 col-lg-offset-2">
        <div class="alert alert-info fade in">
            <h4>User Transaction</h4>
            <hr />

            <dl class="dl-horizontal">
                <dt>
                    @Html.Label("First Name")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.User_Profile.FirstName)
                </dd>

                <dt>
                    @Html.Label("Plan")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Plan_Master.Plan)
                </dd>

                <dt>
                    @Html.Label("Amount")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Amount)
                </dd>

                <dt>
                    @Html.Label("Start Date")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Start_Date)
                </dd>

                <dt>
                    @Html.Label("End Date")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.End_Date)
                </dd>

                <dt>
                    @Html.Label("Payment Status")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Payment_Status)
                </dd>

                <dt>
                    @Html.Label("Transection ID")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Transection_ID)
                </dd>

                <dt>
                    @Html.Label("Status")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Status)
                </dd>

                <dt>
                    @Html.Label("Payment Date")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Payment_Date)
                </dd>

                <dt>
                    @Html.Label("Invoice No")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Invoice_No)
                </dd>

                <dt>
                    @Html.Label("Payment Method")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Payment_Method)
                </dd>

                <dt>
                    @Html.Label("Rate Card")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Rate_Card.Status)
                </dd>
            </dl>
        </div>
    </div>
</div>
<p>

    @Html.ActionLink("Back to List", "Payment", "OtherUsers", new { id = Model.User_ID }, htmlAttributes: new { @class = "btn btn-primary" })
</p>