Lexnarro/Controllers/TransactionHistoryController.cs
using Lexnarro.HelperClasses;
using Lexnarro.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Lexnarro.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TransactionHistoryController : Controller
    {
        private LaxNarroEntities db = null;
        private readonly ToasterMessage toastNotifications = null;


        public TransactionHistoryController()
        {
            db = new LaxNarroEntities();
            toastNotifications = new ToasterMessage();
        }


        public ActionResult Index()
        {
            return View();
        }


        public ActionResult GetData()
        {
            var userTransaction = db.User_Transaction_Master.Include(u => u.User_Profile).
                Include(u => u.Rate_Card).Include(u => u.Plan_Master).ToList();

            var transactions = userTransaction.ToList().Select(item => new
            {
                item.Id,
                item.User_ID,
                Name = item.User_Profile.FirstName + " " + item.User_Profile.LastName,
                item.Plan_Master.Plan,
                item.Amount,
                item.User_Profile.EmailAddress,
                StartDate = item.Start_Date.ToShortDateString(),
                EndDate = item.End_Date.ToString().Split(' ')[0],
                item.Payment_Status,
                item.Transection_ID,
                item.Status,
                PaymentDate = Convert.ToDateTime(item.Payment_Date).ToShortDateString(),//item.Payment_Date.ToString().Split(' ')[0],
                item.Invoice_No
            });

            return Json(new { data = transactions }, JsonRequestBehavior.AllowGet);
        }



        // GET: TransactionHistory
        public ActionResult Details(decimal id)
        {
            User_Transaction_Master userTransaction = db.User_Transaction_Master.Include(u => u.User_Profile).
                Include(u=>u.Rate_Card).Include(u=>u.Plan_Master).Where(u => u.Id == id).SingleOrDefault();


            if (userTransaction == null)
            {
                return HttpNotFound();
            }

            return View(userTransaction);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();

            base.Dispose(disposing);
        }
    }
}

Lexnarro/Views/TransactionHistory/Details.cshtml
@model Lexnarro.Models.User_Transaction_Master

@{
    ViewBag.Title = "PaymentDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var Id = ViewBag.id;
}

<h2>Transaction Details</h2>

<div class="row">
    <div class="form-horizontal col-lg-6 col-lg-offset-2">
        <div class="alert alert-info fade in">
            <h4>User Transaction</h4>
            <hr />

            <dl class="dl-horizontal">
                <dt>
                    @Html.Label("First Name")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.User_Profile.FirstName)
                </dd>

                <dt>
                    @Html.Label("Plan")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Plan_Master.Plan)
                </dd>

                <dt>
                    @Html.Label("Amount")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Amount)
                </dd>

                <dt>
                    @Html.Label("Start Date")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Start_Date)
                </dd>

                <dt>
                    @Html.Label("End Date")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.End_Date)
                </dd>

                <dt>
                    @Html.Label("Payment Status")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Payment_Status)
                </dd>

                <dt>
                    @Html.Label("Transection ID")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Transection_ID)
                </dd>

                <dt>
                    @Html.Label("Status")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Status)
                </dd>

                <dt>
                    @Html.Label("Payment Date")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Payment_Date)
                </dd>

                <dt>
                    @Html.Label("Invoice No")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Invoice_No)
                </dd>

                <dt>
                    @Html.Label("Payment Method")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Payment_Method)
                </dd>

                <dt>
                    @Html.Label("Rate Card")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Rate_Card.Status)
                </dd>
            </dl>
        </div>
    </div>
</div>
<p>

    @Html.ActionLink("Back to list", "Index", "TransactionHistory", new { }, htmlAttributes: new { @class = "btn btn-primary" })
</p>

Lexnarro/Views/TransactionHistory/Index.cshtml
@using Lexnarro.HelperClasses

@{
    ViewBag.Title = "Payment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Transaction List</h2>
<br />
@*<h4><b>Name : <span id="name"></span></b></h4>*@
<br />
<section class="panel">
    <div class="panel-body">
        <table class="table table-hover" id="dataTable">
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>
                        Plan
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Start Date
                    </th>
                    <th>
                        End Date
                    </th>
                    @*<th>
                        Transaction Id
                    </th>*@
                    <th>
                        Payment Date
                    </th>
                    <th>
                        Invoice No
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
            </thead>

        </table>
        <h4>
            <b>
                Total Amount : <span id="totalamount"></span>
            </b>
        </h4>
        <br />

        @*<p>
            @Html.ActionLink("Back to List", "Details", "ActiveUsers", new { id = id }, htmlAttributes: new { @class = "btn btn-primary" })
        </p>*@

    </div>


    @section JavaScript{
        @Html.Raw(ViewBag.message)
    }

    @section scripts
    {
        <script>
            $(function () {
                var userId = @UserHelper.GetUserId();
                var t = $('#dataTable').DataTable({
                    theme: 'bootstrap',
                    responsive: true,
                    autoWidth: false,
                    "footerCallback": function (row, data, start, end, display) {
                        var api = this.api(), data;
                        // Remove the formatting to get integer data for summation
                        var intVal = function (i) {
                            return typeof i === 'string' ? i.replace(/[\$,]/g, '') * 1 : typeof i === 'number' ? i : 0;
                        };

                        // totalAmount over all pages
                        total_amount = api.column(4).data().reduce(function (a, b) {
                            return (intVal(a) + intVal(b)).toFixed(2);
                        }, 0);

                        // total_page_amount over this page
                        total_page_amount = api.column(4, { page: 'current' }).data().reduce(function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0);

                        total_page_amount = parseFloat(total_page_amount);
                        total_amount = parseFloat(total_amount);
                        // Update footer
                        $('#totalamount').html(total_amount);
                    },

                    "columnDefs": [{
                        "searchable": false,
                        "orderable": false,
                        "targets": [0]
                    }],
                    "order": [[1, 'asc']],
                    "ajax": {
                        "url": '/TransactionHistory/GetData',
                        "type": 'get',
                        "datatype": "json"
                    },
                    "columns": [
                        { "data": null },
                        { "data": "Name" },
                        { "data": "EmailAddress" },
                        { "data": "Plan" },
                        { "data": "Amount" },
                        { "data": "StartDate" },
                        { "data": "EndDate" },
                        //{ "data": "Payment_Status" },
                        //{ "data": "Transection_ID" },
                        //{ "data": "Status" },
                        { "data": "PaymentDate" },
                        { "data": "Invoice_No"},
                         {
                             "data": "Id", render: (function (data, type, row) {
                                 //if (row.ID == userId) {
                                 //    return ' <a href="/User/ActiveUserDetails/' + data + '" class="btn btn-primary">Details</a>';
                                 //}
                                 //$('#name').text(row.FirstName + ' ' + row.LastName);
                                 return '<a href="/TransactionHistory/Details/' + data + '" class="btn btn-info">Details</a>';
                             })
                         }
                    ]
                });
                t.on('order.dt search.dt', function () {
                    t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                        cell.innerHTML = i + 1;
                    });
                }).draw();
            });
        </script>
    }
</section>